{{ config(materialized='view') }}

SELECT
    CUSTOMER_ID,
    CUSTOMER_NAME,
    CITY,
    STATE,
    EMAIL,
    CUSTOMER_TIER,
    VALID_FROM,
    VALID_TO,
    IS_CURRENT
FROM ECOMMERCE_DWH.DBT_SKHANDEKAR.DIM_CUSTOMER_SCD2