{{ config(materialized='table') }}

WITH source AS (

    SELECT *
    FROM {{ ref('stg_customer') }}

),

cleaned AS (

    SELECT
        CUSTOMER_ID,
        TRIM(CUSTOMER_NAME) AS CUSTOMER_NAME,
        TRIM(CITY) AS CITY,
        TRIM(STATE) AS STATE,
        LOWER(TRIM(EMAIL)) AS EMAIL,
        UPPER(TRIM(CUSTOMER_TIER)) AS CUSTOMER_TIER,
        UPDATED_AT,

        ROW_NUMBER() OVER (
            PARTITION BY CUSTOMER_ID
            ORDER BY UPDATED_AT DESC
        ) AS RN

    FROM source

    WHERE CUSTOMER_ID IS NOT NULL

)

SELECT
    CUSTOMER_ID,
    COALESCE(CUSTOMER_NAME, 'UNKNOWN') AS CUSTOMER_NAME,
    COALESCE(CITY, 'UNKNOWN') AS CITY,
    COALESCE(STATE, 'UNKNOWN') AS STATE,
    COALESCE(EMAIL, 'UNKNOWN') AS EMAIL,
    COALESCE(CUSTOMER_TIER, 'UNKNOWN') AS CUSTOMER_TIER,
    UPDATED_AT

FROM cleaned

WHERE RN = 1